secrets:
  postgresql_username:
    environment: "POSTGRESQL_USERNAME"
  postgresql_password:
    environment: "POSTGRESQL_PASSWORD"


services:
  download_status_db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRESQL_DATABASE=vkr"
      - "POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME"
      - "POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD"
    secrets:
      - postgresql_username
      - postgresql_password
    volumes:
      - dl-status-db:/bitnami/postgresql


volumes:
  dl-status-db:
