services:
  download_status_db:
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - "6432:5432"
    environment:
      - "POSTGRESQL_DATABASE=vkr"
      - "POSTGRESQL_USERNAME=${DB_USER}"
      - "POSTGRESQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - dl-status-db:/bitnami/postgresql
  vkr_frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - satellite-data:/opt/satellite-data


volumes:
  dl-status-db:
  satellite-data:
