"""Initial

Revision ID: 98655aa8a787
Revises: 
Create Date: 2025-01-26 23:02:25.246995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98655aa8a787"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_status",
        sa.Column("request", sa.String(), nullable=False),
        sa.Column("downloaded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("request"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("download_status")
    # ### end Alembic commands ###
